foolscap-ghost: &foolscap-ghost
  container_name: foolscap-ghost
  build: docker-ghost
  ports:
    - 2368:2368
  environment:
    NODE_ENV: development    
    VIRTUAL_HOST: http://192.168.99.100
    VIRTUAL_PORT: 2368
    GHOST_CONTENT: /var/lib/ghost
    GHOST_SOURCE: /usr/src/ghost
    GHOST_SOURCE_CONTENT: /usr/src/ghost-content
    DOCKER_GHOST: /usr/src/docker-ghost
    GHOST_CONFIG_JS: /usr/src/docker-ghost/config.js
  volumes:
    - /var/lib/ghost
    - ./content/data:/var/lib/ghost/data:rw
    - /var/lib/ghost/apps
    - /var/lib/ghost/images
    - /var/lib/ghost/themes
    - ./casper:/var/lib/ghost/themes/casper:ro
    - ./foolscap-ghost-theme:/var/lib/ghost/themes/foolscap-ghost-theme:ro
    - ./content/:/usr/src/ghost-content/:ro    
    - ./docker-ghost:/usr/src/docker-ghost:ro        
    - ./:/usr/src/foolscap-ghost-docker-compose:ro




